# deepsort.yaml

tracker_type: 'deep_sort'
model_cfg: 'osnet_x0_25'  # DeepSORT'ta kullanılan özellik çıkarıcı model
model_weights: 'osnet_x0_25_msmt17.pt'
max_dist: 0.2
min_confidence: 0.3
nms_max_overlap: 1.0
max_iou_distance: 0.7
max_age: 70
n_init: 3
nn_budget: 100

